# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 生成固件解密json文件

on:
  workflow_dispatch:
  schedule:
   - cron: '0 0,3,5,7,10,12,14,16,18,20 * * *'
  repository_dispatch:
    types: [telegram_trigger]  
jobs:
  decrypt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: 安装python依赖
      run: |
        pip install -r requirements.txt
    - name: 运行解密脚本
      env:
        DATABASE: ${{ secrets.DATABASE }}
        HOST: ${{ secrets.HOST }}
        DBUSER: ${{ secrets.DBUSER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
        FCM_KEY: ${{ secrets.FCM_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        python 三星测试版固件版本号解密.py
    - name: 暂存提交
      run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.USEREMAIL }}
          export TZ='Asia/Shanghai'
          git add -A
          git diff-index --quiet HEAD -- || git commit -m "更新json文件"
    - name: 推送json文件
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


